Refector AUTO_ENC code

diff --git a/AUTO_ENC b/AUTO_ENC
--- a/AUTO_ENC
+++ b/AUTO_ENC
@@ -17,7 +17,7 @@ source_dir=$2
 date_regex="^([0-9]{4})-([0-9]{2})-([0-9]{2})$"
 
 if [[ ! "$1" =~ $date_regex ]]; then
-	echo "ERROR: date must be in the format YYYY-MM-DD" >&2
+	echo "$0 ERROR: date must be in the format YYYY-MM-DD" >&2
 	exit 1
 fi
 
@@ -25,7 +25,7 @@ month="${BASH_REMATCH[2]}"
 
 # check month, must be <= 12
 if [ "$month" -gt "12" ]; then
-	echo "ERROR: month must be 12 or less" >&2
+	echo "$0 ERROR: month must be 12 or less" >&2
 	exit 1
 fi
 
@@ -33,7 +33,7 @@ day="${BASH_REMATCH[3]}"
 
 # check day, must be <= 31
 if [ "$day" -gt "31" ]; then
-	echo "ERROR: day must be 31 or less" >&2
+	echo "$0 ERROR: day must be 31 or less" >&2
 	exit 1
 fi
 
@@ -42,50 +42,59 @@ fi
 # check source directory
 # must be one of today, friday, weekend, holiday
 if [[ ! "$source_dir" =~ ^(today|friday|weekend|holiday)$ ]]; then
-	echo -e "ERROR: source directory must be one of:\n\
+	echo -e "$0 ERROR: source directory must be one of:\n\
 today\nfriday\nweekend\nholiday" >&2
 	exit 1
 fi
 
-#####################################################################
+######################################################################
 
+# remove $1 and $2 from list of arguments
 shift 2
 
-segment_regex="^[0-9]+$"
+segment_regex="^[1-7]+$"
 segment_list="$@"
 success_array=()
 failure_array=()
 
 while (( "$#" )); do # loop through segment numbers
-	if [[ ! "$1" =~ $segment_regex ]]; then
-		echo "ERROR: $1 must be a number!" >&2
-		echo "Skipping $1..."
-		shift
-		continue
-	fi
-	
-	./ENC $name_date $source_dir $1	
 
 	echo "---------------------------------------"
-echo "$?"
-	# if ./ENC exited successfully...
-	if [ "$?" -eq "0" ]; then
-		echo "Segment $1 complete !!!!!!"
-		success_array+=("$1")
-	else
-		echo "ERROR: something bad happened; segment $1 failed!!" >&2
-		failure_array+=("$1")
-	fi
 
+	if [[ ! "$1" =~ $segment_regex ]]; then
+		echo "$0 ERROR: $1 must be a number! (between 1-7 inclusive)" >&2
+		echo "Skipping $1..."
+		sleep 2s
+		#shift
+		#continue
+	else
+		./ENC $name_date $source_dir $1	
+		enc_status="$?"
+	
+		# if ./ENC exited successfully...
+		if [ "$enc_status" -eq "0" ]; then
+			echo "Segment $1 complete !!!!!!"
+			success_array+=("$1")
+		else
+			echo "$0 ERROR: something bad happened; segment $1 failed!!" >&2
+			failure_array+=("$1")
+		fi
+	
+		#shift
+	fi
+	
 	shift
 done
 
 echo "---------------------------------------"
 echo "These segments were given: $segment_list"
-echo "These segments were processed: ${success_array[@]}"
+
+if [ -n "$success_array" ]; then
+	echo "These segments were processed: ${success_array[@]}"
+	echo "DONE !!!!!! without failures"
+fi
 
 if [ -n "$failure_array" ]; then
 	echo "These segments failed: ${failure_array[@]}" >&2
+	echo "DONE !!!!!! with failures"
 fi
-
-echo "DONE !!!!!!"
