Edit CLEANUP Script
A few changes have been made to the CLEANUP script:

 - Added the working directory /home/encoder/w as a variable, WORK_DIR.

 - Added a conditional to make sure we are in the working directory when
   the script is run.

 - The 'mv' now incorporates the $WORK_DIR variable.

 - The script now explicitly runs 'rm' from the working directory.

diff --git a/CLEANUP b/CLEANUP
--- a/CLEANUP
+++ b/CLEANUP
@@ -1,6 +1,19 @@
-mv /home/encoder/w/done_archive/sk/out/*.mp4 /home/encoder/w/done_archive/sk/old/
-rm -f ./*.mp4
-rm -f ./*.mp3
-rm -f ./*.mov
-rm -f ./ffmpeg2pass*
+#!/bin/sh
+
+WORK_DIR="/home/encoder/w"
+
+# make sure we are in the working directory
+if [ "$(pwd)" != "$WORK_DIR" ]; then
+  echo "ERROR: MUST BE IN DIRECTORY: /home/encoder/w" >&2
+  exit 1
+fi
+
+echo "Running Cleanup !!!!!!"
+
+mv ${WORK_DIR}/done_archive/sk/out/*.mp4 ${WORK_DIR}/done_archive/sk/old/
+
+rm -f ${WORK_DIR}/*.mp4
+rm -f ${WORK_DIR}/*.mp3
+rm -f ${WORK_DIR}/*.mov
+rm -f ${WORK_DIR}/ffmpeg2pass*
 ssh USER@REMOTE_HOST 'cd REMOTE_DIRECTORY;./.cleanup'
