Add frame rate check to ENC

diff --git a/ENC b/ENC
--- a/ENC
+++ b/ENC
@@ -1,6 +1,10 @@
-#!/bin/sh
+#!/bin/bash
 
-if [ "$#" -ne 3 ] ; then
+pv=/usr/bin/pv
+ffprobe=/usr/bin/ffprobe
+opts=( -v error -select_streams v -show_entries stream=r_frame_rate -of csv=p=0 )
+
+if [ "$#" -ne "3" ] ; then
   echo "Usage: $0 YYYY-MM-DD Source_Folder  segment_number" >&2
   echo "Ex: $0 2014-03-09 today  2" >&2
   echo "Ex: $0 2014-11-28 weekend  1" >&2
@@ -8,11 +12,21 @@ if [ "$#" -ne 3 ] ; then
   exit 1
 fi
 
-
 name_date=$1
 source_dir=$2
 segment_idx=$3
-cp  ${source_dir}/${segment_idx}.mov  female_show_${name_date}_hd_${segment_idx}.mov
+real_frame_rate=$(${ffprobe} "${opts[@]}" "${source_dir}/${segment_idx}.mov")
+frame_rate="${real_frame_rate%/*}"
+truncated_fr="${frame_rate:0:2}"
+
+# make sure the frame rate is 30
+if [ "${frame_rate}" -ne "30000" ]; then
+	echo "ERROR!!!! Segment does not have a frame rate of 30 !!" >&2
+	echo "Frame rate is ${truncated_fr}" >&2
+	exit 1
+fi
+
+${pv} "${source_dir}/${segment_idx}.mov" > "female_show_${name_date}_hd_${segment_idx}.mov"
 
 if [ "$?" -eq "0" ]; then
 	./sk_encode.sh female_show_${name_date}_hd_${segment_idx}.mov
@@ -20,4 +34,3 @@ else
 	echo "$0 ERROR: cp from working directory failed" >&2
 	exit 1
 fi
-
