Add second DP code to LAZY_PROMO

diff --git a/LAZY_PROMO b/LAZY_PROMO
--- a/LAZY_PROMO
+++ b/LAZY_PROMO
@@ -14,9 +14,10 @@ if [ "$#" -gt 0 ]; then
 fi
 
 weekday_name="$(date +%A)"
-month="$(date +%b%d)"
-month_str="$(date +%b)"
-month_num="$(date +%d)"
+month_and_day="$(date +%b%d)"
+month_short="$(date +%b)"
+day_num="$(date +%d)"
+full_date="$(date +%Y-%m-%d)"
 
 
 # Day of the week can only be a weekday.
@@ -30,15 +31,31 @@ else
 	source_dir="today"
 fi
 
-file_path="${source_dir}/DP_${month}.mov"
+file_path_nude="${source_dir}/DP_${month_and_day}.mov"
+file_path_social="${source_dir}/DP_${month_and_day}_social.mov"
  
-if [[ ! -f "$file_path" ]]; then
-	echo "$0 ERROR: DP not found in directory ${source_dir}!!!" >&2
+if [[ ! -f "$file_path_nude" ]]; then
+	echo "$0 ERROR: Nude DP not found in directory ${source_dir}!!!" >&2
 	exit 1
 fi
 
-new_name="program_promo_hd_welcome_${month}.mov"
+if [[ ! -f "$file_path_social" ]]; then
+	echo "$0 ERROR: Social DP not found in directory ${source_dir}!!!" >&2
+	exit 1
+fi
 
-echo "Filename is: $new_name !!!!!!"
-cp $file_path ${new_name}
-./sk_encode.sh ${new_name}
+new_name_nude="program_promo_nude_${full_date}.mov"
+new_name_social="program_promo_social_${full_date}.mov"
+
+echo "Filename one is: $new_name_nude !!!!!!"
+echo "Filename two is: $new_name_social !!!!!!"
+sleep 2
+
+cp $file_path_nude ${new_name_nude}
+./sk_encode.sh ${new_name_nude}
+echo "${new_name_nude} Complete !!!!"
+sleep 2
+
+cp $file_path_social ${new_name_social}
+./sk_encode.sh ${new_name_social}
+echo "${new_name_social} Complete !!!!"
